[workspace]

[package]
name = "resonant-no-std-check"
version = "0.0.1"
edition = "2021"
publish = false

[dependencies]
resonant-core = { path = "../../resonant-core", default-features = false }
resonant-fft = { path = "../../resonant-fft", default-features = false }
resonant-filters = { path = "../../resonant-filters", default-features = false }
cortex-m-rt = "0.7"
cortex-m-semihosting = "0.5"
panic-semihosting = "0.6"

[profile.dev]
opt-level = 1

[profile.release]
opt-level = "s"
lto = true
